version: '3.8'

services:
  django:
    build: ./django
    container_name: django_app
    env_file: ./django/.env
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - nestjs

  nestjs:
    build: ./nestjs/backend
    container_name: nestjs_app
    env_file: ./nestjs/backend/.env
    volumes:
      - ./nestjs/backend:/app
    ports:
      - "3003:3003"

